# Introduction to Financial Python
## NumPy and Basic Pandas

### Introduction
Now that we have introduced the fundamentals of Python, it's time to learn about NumPy and Pandas.



### NumPy
NumPy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. It also has strong integration with Pandas, which is another powerful tool for manipulating financial data.

Python packages like NumPy and Pandas contain classes and methods which we can use by importing the package:

In [ ]:
import numpy as np

**Basic NumPy Arrays**

A NumPy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. Here we make an array by passing a list of Apple stock prices:

In [ ]:
price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print(price_array, type(price_array))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>


Notice that the type of array is "ndarray" which is a multi-dimensional array. If we pass np.array() a list of lists, it will create a 2-dimensional array.

In [ ]:
Ar = np.array([[1,3],[2,4]])
print(Ar, type(Ar))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>


We get the dimensions of an ndarray using the .shape attribute:

In [ ]:
print(Ar.shape)

(2, 2)


If we create an 2-dimensional array (i.e. matrix), each row can be accessed by index:

In [ ]:
print(Ar[0])
print(Ar[1])

[1 3]
[2 4]


If we want to access the matrix by column instead:

In [ ]:
print('the first column: ', Ar[:,0])
print('the second column: ', Ar[:,1])

the first column:  [1 2]
the second column:  [3 4]


**Array Functions**

Some functions built in NumPy that allow us to perform calculations on arrays. For example, we can apply the natural logarithm to each element of an array:

In [ ]:
print(np.log(price_array))

[4.96793654 4.98244156 4.9675886  4.96995218 4.96633504 4.96018375]


Other functions return a single value:

In [ ]:
print(np.mean(price_array))
print(np.std(price_array))
print(np.sum(price_array))
print(np.max(price_array))

143.89666666666668
0.9673790478515796
863.38
145.83


The functions above return the mean, standard deviation, total and maximum value of an array.

**Mi ejemplo para esta sección:**

In [ ]:
#Programa que retorna la matriz traspuesta a otra 
Matriz = [[1,  2,  3,  4,  5 ],
          [6,  7,  8,  9,  10], 
          [11, 12, 13, 14, 15], 
          [16, 17, 18, 19, 20], 
          [21, 22, 23, 24, 25]]#Escribir aquí la matriz a sacar traspuesta con cualquier longitud
ArrayMatriz = np.array(Matriz)
LX = len(ArrayMatriz[0])
LY = len(ArrayMatriz)

print("Matriz:\n", ArrayMatriz)
MatrizTraspuesta = []

for i in range(LX):
  TempFila = []
  for j in range(LY):
    TempFila.append(0)
  MatrizTraspuesta.append(TempFila)
MTArray = np.array(MatrizTraspuesta)
for i in range(LX):
  for j in range(LY):
    MTArray[i, j] = ArrayMatriz[j, i]
print("Traspuesta:\n", MTArray)

### Pandas
Pandas is one of the most powerful tools for dealing with financial data. First we need to import Pandas:

In [ ]:
import pandas as pd

**Series**

Series is a one-dimensional labeled array capable of holding any data type (integers, strings, float, Python object, etc.)

We create a Series by calling pd.Series(data), where data can be a dictionary, an array or just a scalar value.

In [ ]:
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
s

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64

We can customize the indices of a new Series:

In [ ]:
s = pd.Series(price,index = ['a','b','c','d','e','f'])
s

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64

Or we can change the indices of an existing Series:

In [ ]:
s.index = [6,5,4,3,2,1]
s

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64

Series is like a list since it can be sliced by index:

In [ ]:
print(s[1:])
print(s[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64


Series is also like a dictionary whose values can be set or fetched by index label:

In [ ]:
print(s[4])
s[4] = 0
print(s)

143.68
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64


Series can also have a name attribute, which will be used when we make up a Pandas DataFrame using several series.

In [ ]:
s = pd.Series(price, name = 'Apple Price List')
print(s)
print(s.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Price List, dtype: float64
Apple Price List


We can get the statistical summaries of a Series:

In [ ]:
print (s.describe())

count      6.000000
mean     143.896667
std        1.059711
min      142.620000
25%      143.545000
50%      143.705000
75%      143.947500
max      145.830000
Name: Apple Price List, dtype: float64


**Mi ejemplo**

In [ ]:
price2 = [100, 200, 300, 400, 300, 200]
s2 = pd.Series(price2)
print(s2,"\n\n")
s2 = pd.Series(price2,index = ['a','b','c','d','e','f'])
print(s2,"\n\n")
print(s2[1:],"\n\n")
print(s2[:-2],"\n\n")
print (s2.describe())

0    100
1    200
2    300
3    400
4    300
5    200
dtype: int64 


a    100
b    200
c    300
d    400
e    300
f    200
dtype: int64 


b    200
c    300
d    400
e    300
f    200
dtype: int64 


a    100
b    200
c    300
d    400
dtype: int64 


count      6.000000
mean     250.000000
std      104.880885
min      100.000000
25%      200.000000
50%      250.000000
75%      300.000000
max      400.000000
dtype: float64


**Time Index**

Pandas has a built-in function specifically for creating date indices: pd.date_range(). We use it to create a new index for our Series:



In [ ]:
time_index = pd.date_range('2017-01-01',periods = len(s),freq = 'D')
print(time_index)
s.index = time_index
print(s)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Price List, dtype: float64


Series are usually accessed using the iloc[] and loc[] methods. iloc[] is used to access elements by integer index, and loc[] is used to access the index of the series.

iloc[] is necessary when the index of a series are integers, take our previous defined series as example:

In [ ]:
s.index = [6,5,4,3,2,1]
print(s)
print(s[1])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Price List, dtype: float64
142.62


If we intended to take the second element of the series, we would make a mistake here, because the index are integers. In order to access to the element we want, we use iloc[] here:

In [ ]:
print(s.iloc[1])

145.83


While working with time series data, we often use time as the index. Pandas provides us with various methods to access the data by time index.

In [ ]:
s.index = time_index
print(s['2017-01-03'])

143.68


We can even access to a range of dates:



In [ ]:
print(s['2017-01-02':'2017-01-05'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Price List, dtype: float64


Series[] provides us a very flexible way to index data. We can add any condition in the square brackets:

In [ ]:
print(s[s < np.mean(s)] )
print([(s > np.mean(s)) & (s < np.mean(s) + 1.64*np.std(s))])

2017-01-01    143.73
2017-01-03    143.68
2017-01-05    143.50
2017-01-06    142.62
Name: Apple Price List, dtype: float64
[2017-01-01    False
2017-01-02    False
2017-01-03    False
2017-01-04     True
2017-01-05    False
2017-01-06    False
Freq: D, Name: Apple Price List, dtype: bool]


As demonstrated, we can use logical operators like & (and), | (or) and ~ (not) to group multiple conditions.

**Mi ejemplo**

In [ ]:
time_index2 = pd.date_range('2018-01-01',periods = len(s2),freq = 'M')
print(time_index2)
s2.index = time_index2
print(s2)
print(s2[s2 < np.mean(s2)] )
print([(s2 > np.mean(s2))])

DatetimeIndex(['2018-01-31', '2018-02-28', '2018-03-31', '2018-04-30',
               '2018-05-31', '2018-06-30'],
              dtype='datetime64[ns]', freq='M')
2018-01-31    100
2018-02-28    200
2018-03-31    300
2018-04-30    400
2018-05-31    300
2018-06-30    200
Freq: M, dtype: int64
2018-01-31    100
2018-02-28    200
2018-06-30    200
dtype: int64
[2018-01-31    False
2018-02-28    False
2018-03-31     True
2018-04-30     True
2018-05-31     True
2018-06-30    False
Freq: M, dtype: bool]


**Mi ejemplo para esta sección**

In [ ]:
new_indexl = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i','j', 'k' ,'l', 'm', 'n', 'ñ', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x','y', 'z']
serieLetras = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])
serieLetras.name = "Serie de letras"
serieLetras.index = new_indexl
print(serieLetras.name, '\n', serieLetras)
print(len(serieLetras))
print(np.mean(serieLetras))

Serie de letras 
 a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
ñ    15
o    16
p    17
q    18
r    19
s    20
t    21
u    22
v    23
w    24
x    25
y    26
z    27
Name: Serie de letras, dtype: int64
27
14.0


## Summary
Here we have introduced NumPy and Pandas for scientific computing in Python. In the next chapter, we will dive into Pandas to learn resampling and manipulating Pandas DataFrame, which are commonly used in financial data analysis.